name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - dev

jobs:
  render_diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: dev

      # SỬA DÒNG NÀY: Chỉ định rõ vào đúng thư mục lồng chứa file .puml
      - name: Process PlantUML Files
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tpng -o "" "HorseRacingProject/HorseRacingAPI/Docs/*.puml"

      # SỬA DÒNG NÀY: Cho phép bot add tất cả file png được tạo ra
      - name: Commit and Push the New Generated Images
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add HorseRacingProject/HorseRacingAPI/Docs/*.png
          git diff-index --quiet HEAD || git commit -m "Bot: Automatically updated architecture diagrams [skip ci]"
          git push origin dev